#!/usr/bin/env python3
"""Generate the offline-resampler Q24 windowed-sinc table; no runtime FPU."""
import math
from pathlib import Path

def table():
    coefficients=[]
    for i in range(4097):
        x=i/256
        sinc=1 if not i else math.sin(math.pi*x)/(math.pi*x)
        window=.42+.5*math.cos(math.pi*x/16)+.08*math.cos(2*math.pi*x/16)
        coefficients.append(round(sinc*window*(1<<24)))
    return ('/* Generated by tools/generate_sinc_kernel.py; Q24, 256 steps per zero crossing. */\n'
            'static const int32_t pt_filter_kernel[4097]={\n'+
            ',\n'.join(','.join(str(v) for v in coefficients[i:i+8]) for i in range(0,len(coefficients),8))+'\n};\n')

if __name__=='__main__':
    (Path(__file__).resolve().parents[1]/'src/core/sinc_kernel.h').write_text(table())
