"""Private SOURCE proposal: Root admits/runs current default factory24 once.
Historical archive driver untouched. Genuine original fixture bytes unchanged.
Includes inherited queue main plus constructor suites; no renamed uncalled main.
"""
from pathlib import Path
import os, subprocess, tempfile, unittest
ROOT = Path('/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A')
SOURCES = ['/Users/james1/Documents/Codex/2026-09-18/rev/outputs/sampler-default-factory-current-source-20261010-v1/source/tests/sampler_mixed_readers_test.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/editor/sampler_mixed_readers.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/amigus_trigger_levels.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/mixed_readers_causal.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/mixed_scheduled_readers.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/elapsed_clock.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/editor/sampler_paula.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/editor/sampler_wavetable.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/amigus_voice_plan.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/editor/sampler.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/editor/slots.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/pcm_filtered.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/slices.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/pattern.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/document.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/pp20.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/project.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/mod_project.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/mod_inspect.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/channels.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/pcm.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/wav.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/svx.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/raw.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/amigus_reservation.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/amigus_wavetable_cache.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/amigus_sample_ram.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/sample_cache.c', '/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core/playback_pcm.c']
FLAGS = ['-std=c99', '-O1', '-g', '-Wall', '-Wextra', '-Werror', '-UNDEBUG', '-fsanitize=address,undefined', '-I/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/src/core', '-I/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A', '-I/Users/james1/Documents/Codex/2026-09-18/rev/work/Protracker-2.4A/tests']
ORACLE = b'SAMPLER MIXED FACTORY PASS:24 genuine16-reader paired8/16/24 master lifetimes; real private validation and persistent/TEMP pins; selective signed8 Chip and8/16 card literal endian/channel/padding oracles; exact saves/grid/independent proof orders; constructor/admission/all-phase cancel/source expiry/alias/reentry/fragmented cache-slot2 arena-block0; factory queued effects/unadopted pins/CONTROL+STOP/output guards/budget;6 released caller/current persistent-pin lifetimes;32-reader replacement/pressure and malformed exact-domain drains; SOFTWARE_ONLY\nMIXED READERS PASS:12 genuine16-action paired lifetimes;20 constructor/180 typed admissions;78 callback/effect/proof cases;24 explicit clock/refusal/pending/cancellation groups;6 malformed-reader envelopes;18 endian/loop/padding groups;6 full alias,32-reader capacity/replacement and control/STOP groups; expired controls/consumed close0; exact common grid/master saves; SOFTWARE_ONLY\namigus reservation lifecycle: PASS (fake library, no hardware)\nWAVETABLE UPLOAD JOB PASS: bounded steps, cancellation, unpublished leases, partial words, live ownership loss and hit transfer; injected only\nAMIGUS WAVETABLE OWNER PASS: explicit resource, pinned cache lifetime, failure cleanup, lost ownership refusal; fake library/bus only\n'
class CurrentDefaultFactory24(unittest.TestCase):
 def test_actual_current_default_common_open(self):
  env = dict(os.environ, ASAN_OPTIONS='halt_on_error=1:abort_on_error=1', UBSAN_OPTIONS='halt_on_error=1:print_stacktrace=1')
  with tempfile.TemporaryDirectory(prefix='pt-current-default-factory24-') as temporary:
   exe = Path(temporary)/'fixture'
   compiled = subprocess.run(['/usr/bin/cc', *FLAGS, *SOURCES, '-o', str(exe)], cwd=ROOT, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True, timeout=120)
   self.assertEqual(compiled.stdout,b''); self.assertEqual(compiled.stderr,b'')
   actual = subprocess.run([str(exe)], cwd=ROOT, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True, timeout=30)
   self.assertEqual(actual.stderr,b''); self.assertEqual(actual.stdout, ORACLE)
if __name__ == '__main__': unittest.main()
